import json
import logging
from datetime import date
from pathlib import Path

from src.config import REPORTS_PATH
from src.state import AgentState

logger = logging.getLogger(__name__)


async def reporting_node(state: AgentState) -> dict:
    """
    Format the analysis JSON into a markdown report and write it to disk.
    Runs even on error so that failed runs are always documented.
    """
    run_date = state.get("run_date", date.today().isoformat())

    if state.get("error"):
        md = f"# Elis Energy Report — {run_date}\n\n**Run failed:** {state['error']}\n"
        _write_report(run_date, md)
        return {"summary_markdown": md}

    try:
        analysis = json.loads(state.get("analysis_json", "{}"))
        md = _format_report(analysis, run_date)
        _write_report(run_date, md)
        return {"summary_markdown": md}

    except Exception as exc:
        logger.error("Reporting failed: %s", exc, exc_info=True)
        md = f"# Elis Energy Report — {run_date}\n\n**Report generation failed:** {exc}\n"
        return {"summary_markdown": md}


def _write_report(run_date: str, content: str) -> None:
    reports_dir = Path(REPORTS_PATH)
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"report-{run_date}.md"
    path.write_text(content, encoding="utf-8")
    logger.info("Report written to %s", path)


def _format_report(analysis: dict, run_date: str) -> str:
    recs = analysis.get("recommendations", [])
    recs_md = "\n".join(f"- {r}" for r in recs) if recs else "- No specific recommendations"

    min_p = analysis.get("today_min_price", {})
    max_p = analysis.get("today_max_price", {})

    return f"""# Elis Energy Report — {run_date}

## Summary
{analysis.get("summary", "No summary available.")}

## Price Analysis
| Metric | Value |
|---|---|
| Price level | **{analysis.get("price_level", "N/A")}** |
| Historical percentile | {analysis.get("price_percentile", "N/A")}th (4-year range) |
| Today's average | {_fmt_price(analysis.get("today_avg_price"))} SEK/kWh |
| Cheapest hour | {_fmt_hour(min_p)} |
| Most expensive hour | {_fmt_hour(max_p)} |

## Consumption
**Anomaly:** {analysis.get("consumption_anomaly") or "None detected"}

## Potential Savings
**Estimated daily savings:** {analysis.get("estimated_daily_savings_sek", 0):.2f} SEK
(by shifting flexible loads to off-peak hours)

## Recommendations
{recs_md}

---
*Generated by Elis Agent*
"""


def _fmt_price(value) -> str:
    if value is None:
        return "N/A"
    return f"{float(value):.4f}"


def _fmt_hour(hour_data: dict) -> str:
    if not hour_data:
        return "N/A"
    hour = hour_data.get("hour", "?")
    price = hour_data.get("price")
    price_str = f"{float(price):.4f}" if price is not None else "?"
    return f"{hour}:00 ({price_str} SEK/kWh)"
